default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: joelportfolio
  pool: 5
  username:
  password: password2

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username:
  password: password1

production:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username:
  password: password1
